### PR TITLE
The ability to work with CESM data using ERA_Fields_New.py and Learn2…

### PR DESCRIPTION
**Pull request by georgemilosh**
Handling of data a bit different given specificities of CESM
Small fixes in tutorial.ipynb

### CODE REVIEW

**Comment by georgemilosh** [comment]
@AlessandroLovo , it allows me to merge, but I think it would be a good idea if you have a look. I am modifying some core functionality.

**Comment by AlessandroLovo** [comment]
I wrote some comments on your changes. The one I am most concerned about is the manipulation of the latitude. Have you checked that it doesn't break Plasim data?

**Comment by georgemilosh** [comment]
I am running some tests. Like making plots and some CNN training. The reason I have this sorting of latitudes is because Plasim and CESM have opposite ordering. So I put something to enforce the sorting consistent with Plasim. With that being said, as you indicate, it would be desirable to sort the latitudes in default case as well.

Concerning the point about using Model to decide where the data comes from, this would be ok, but current implementation gives us more flexbility where data could come from.

**Comment by georgemilosh** [comment]
So I decided to move the sorting into a separate `Plasim_field` class method which is called in `Learn2_new.py: load_data()`

**Comment by georgemilosh** [comment]
Ok, on my side the tests look good. I think it would be nice to merge pull request soon

**Comment by georgemilosh** [comment]
Also the changes you proposed seem to work, @AlessandroLovo

**Comment by georgemilosh** [comment]
Actually there is one more point that is worth doing. I think it would be better for `fields_infos` to be loaded from a json file, like we do with config.json. This is because I would like to keep the labels of the fields, while working with both `CESM` and `Plasim`

**Comment by AlessandroLovo** [comment]
Maybe make a separate issue for that?

**Review by AlessandroLovo — COMMENTED** [review]
All clear

**Pull request merged**
